apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: bot-boxy
    workspace: 
  - imageName: django-boxy
    workspace: django/
deploy:
  kubectl:
    manifests:
      - ./k8s-spec-test/*